### ISSUE TITLE
How to use SelectorAnd?

### ISSUE THREAD

**Issue by WENGSYX** [deepmind/tracr#4]
prev_copy = rasp.SelectorAnd(
      rasp.Select(sop, sop, rasp.Comparison.EQ),
      rasp.Select(rasp.indices, rasp.indices, rasp.Comparison.LT),
    )
    return rasp.Aggregate(prev_copy, rasp.Full(1), default=0) > 0
    
    When “compiling.compile_rasp_to_model”:
    TypeError: Compiling composite Selectors is not supported. Got a <tracr.rasp.rasp.SelectorAnd object at 0x00000207D807F1C0>.

**Comment by WENGSYX** [comment]
And SelectorOr, SelectorNot

**Comment by vmikulik** [comment]
Hi,

This is a known issue -- unfortunately there's no efficient general way to compose selectors, so we don't support it currently.

As a workaround, if you need composite selectors, you can do the following:

```
sop_with_index = rasp.SequenceMap(lambda x, y: (x, y), sop, rasp.indices)
prev_copy = rasp.Select(sop_with_index, sop_with_index, lambda k, q: k[0] == q[0] and k[1] < q[1])   
```

However, this construction will make your model quite big quite quickly if used often.
