### ISSUE TITLE
How to save the model

### ISSUE THREAD

**Issue by WENGSYX** [deepmind/tracr#5]
After I get a model, I want to save it. How do I do it?

for example:
```python
assembled_model = compiling.compile_rasp_to_model(
      program=program,
      vocab=vocab,
      max_seq_len=6,
      causal=False,
      compiler_bos="bos",
      compiler_pad="pad",
      mlp_exactness=100)

import pandas as pd
pd.to_pickle(assembled_model,'add.cnn')
```
AttributeError: Can't pickle local object 'without_apply_rng.<locals>.apply_fn'

**Comment by mrahtz** [comment]
Pickle's inability to handle things like this is unfortunately a well-known problem. Try using `cloudpickle` or `dill` instead.
