### ISSUE TITLE
I want to achieve the Aggregate of all values, but I don't want to average them.

### ISSUE THREAD

**Issue by WENGSYX** [deepmind/tracr#6]
I want to achieve the aggregation of values, but I don't want to average them. How should I achieve this?
```
def turn_number(sop) -> rasp.SOp:
    """Convert the token in the form of categorical to the form of numerical.
    Example usage:
      text = turn_number(tokens)
      text(["0", "0", "0", "5", "6"])
      >> [56, 56, 56, 56, 56]
    Args:
      sop: Sop to turn numerical.
    """
    indice = rasp.Map(lambda x: '0'*x ,length-rasp.indices-1) # Like [10000, 1000, 100, 10, 1]
    sop = rasp.SequenceMap(lambda x,y: float(str(x)+y),sop,indice) # Value alignment of each bit. Like [0, 0, 0, 50, 6]
    sop = rasp.SequenceMap(lambda x,y: x * y,sop,length) # Before aggregation, multiply the length (because the result of aggregation is average).
    out = rasp.numerical(rasp.Aggregate(rasp.Select(rasp.indices,rasp.indices,rasp.Comparison.TRUE),rasp.numerical(rasp.Map(lambda x: x, sop)),default=0)) # Add each bit.
    return out
```

I have created a method to convert a list of tokens, such as [0, 0, 0, 5, 6], into a single value of 56. The method involves multiplying the length of the list with the token values, and then aggregating without averaging. However, this method takes a long time to execute, and for larger values, it can produce calculation errors. 

Please tell me how to solve it

**Comment by david-lindner** [comment]
Tracr currently only supports the standard aggregate operation from RASP (that computes the average), and "selector width" which computes the number of 1 entries in a selector. Everything else must be implemented in terms of these.

Your code seems like a reasonable way of implementing what you want. I'd probably not use strings but rather something like
```
reverse_indices = rasp.numerical(length-rasp.indices-1)
indice = rasp.numerical(rasp.Map(lambda x: 10 ** x, reverse_indices)) # [10000, 1000, 100, 10, 1]
sop = rasp.numerical(rasp.SequenceMap(lambda x, y: x*y, sop, indice)) # [0, 0, 0, 50, 6]
sop = rasp.numerical(rasp.SequenceMap(lambda x, y: x*y, sop, length))
out = rasp.numerical(rasp.Aggregate(rasp.Select(rasp.indices, rasp.indices, rasp.Comparison.TRUE), sop), default=0))
```
By making sure all sops are encoded as numerical, this should make the compiled model more efficient. I'm not sure at which point you get numerical errors, but maybe this version will also help with that.

**Comment by WENGSYX** [comment]
> Tracr currently only supports the standard aggregate operation from RASP (that computes the average), and "selector width" which computes the number of 1 entries in a selector. Everything else must be implemented in terms of these.
> 
> Your code seems like a reasonable way of implementing what you want. I'd probably not use strings but rather something like
> 
> ```
> reverse_indices = rasp.numerical(length-rasp.indices-1)
> indice = rasp.numerical(rasp.Map(lambda x: 10 ** x, reverse_indices)) # [10000, 1000, 100, 10, 1]
> sop = rasp.numerical(rasp.SequenceMap(lambda x, y: x*y, sop, indice)) # [0, 0, 0, 50, 6]
> sop = rasp.numerical(rasp.SequenceMap(lambda x, y: x*y, sop, length))
> out = rasp.numerical(rasp.Aggregate(rasp.Select(rasp.indices, rasp.indices, rasp.Comparison.TRUE), sop), default=0))
> ```
> 
> By making sure all sops are encoded as numerical, this should make the compiled model more efficient. I'm not sure at which point you get numerical errors, but maybe this version will also help with that.

In fact, I was the first to use this method, but the “reverse_indices" is a numerical type, which is not supported by SequenceMap.

```
    sop = rasp.numerical(rasp.SequenceMap(lambda x, y: x * y, sop, length))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

```

**Comment by david-lindner** [comment]
You are right, SequenceMaps with numerical inputs are currently not supported by the compiler. Unfortunately, the categorical embeddings will make the resulting model very large in your case, which results in the long run times you observed. I don't see a good way to avoid this with the currently supported features in Tracr. Eventually, we hope to support more operations with numerical encodings to allow implementing more efficient models for cases like yours. For now you'll probably have to only look at very short context sizes, or consider implement a different program.
